// ============================================================
// InvoForge — Invoice Utilities
// Developer: Ritwik Das | ritwikdas100@gmail.com
// ============================================================

import { InvoiceData, InvoiceItem, InvoiceCalculations } from "@/types/invoice";
import { formatCurrency } from "./calculations";
import { INVOICE_NUMBER_PREFIX } from "./constants";

/**
 * Generate a unique invoice number in INV-YYYY-NNN format
 */
export function generateInvoiceNumber(existingCount = 0): string {
  const year = new Date().getFullYear();
  const count = String(existingCount + 1).padStart(3, "0");
  return `${INVOICE_NUMBER_PREFIX}-${year}-${count}`;
}

/**
 * Generate a unique ID
 */
export function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

/**
 * Format a date string to display format (DD MMM YYYY)
 */
export function formatDate(dateString: string): string {
  if (!dateString) return "";
  const date = new Date(dateString);
  return date.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

/**
 * Get today's date in YYYY-MM-DD format (for form defaults)
 */
export function getTodayISO(): string {
  return new Date().toISOString().split("T")[0];
}

/**
 * Get a date N days from today in YYYY-MM-DD format
 */
export function getDateAfterDays(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split("T")[0];
}

/**
 * Create a new blank invoice item
 */
export function createBlankItem(): InvoiceItem {
  return {
    id: generateId(),
    name: "",
    description: "",
    quantity: 1,
    unitPrice: 0,
  };
}

/**
 * Build a plain-text invoice summary for clipboard copy
 */
export function buildInvoiceSummary(
  invoice: InvoiceData,
  calcs: InvoiceCalculations
): string {
  const lines: string[] = [
    `INVOICE SUMMARY`,
    `===============`,
    `Invoice #: ${invoice.metadata.invoiceNumber}`,
    `Date: ${formatDate(invoice.metadata.invoiceDate)}`,
    `Due Date: ${formatDate(invoice.metadata.dueDate)}`,
    `Status: ${invoice.metadata.status.toUpperCase()}`,
    ``,
    `FROM: ${invoice.business.name}`,
    `GST: ${invoice.business.gstNumber}`,
    ``,
    `TO: ${invoice.client.name}${invoice.client.company ? ` (${invoice.client.company})` : ""}`,
    ``,
    `ITEMS:`,
    ...invoice.items.map(
      (item, i) =>
        `  ${i + 1}. ${item.name} — Qty: ${item.quantity} × ${formatCurrency(item.unitPrice)} = ${formatCurrency(item.quantity * item.unitPrice)}`
    ),
    ``,
    `Subtotal:  ${formatCurrency(calcs.subtotal)}`,
    `GST (${invoice.gstRate}%): ${formatCurrency(calcs.gstAmount)}`,
    `GRAND TOTAL: ${formatCurrency(calcs.grandTotal)}`,
    ``,
    `Generated by InvoForge — https://invoforge.vercel.app`,
  ];

  return lines.join("\n");
}

/**
 * Validate a GST number format (basic Indian GST pattern)
 */
export function isValidGSTNumber(gst: string): boolean {
  const gstPattern = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
  return gstPattern.test(gst.toUpperCase());
}

/**
 * Deep clone an invoice data object
 */
export function cloneInvoice(invoice: InvoiceData): InvoiceData {
  return JSON.parse(JSON.stringify(invoice));
}

/**
 * Create a default empty invoice data structure
 */
export function createDefaultInvoice(): InvoiceData {
  const today = getTodayISO();
  return {
    id: generateId(),
    business: {
      name: "VRF Labs",
      gstNumber: "22AAAAA0000A1Z5",
      email: "ritwikdas100@gmail.com",
      phone: "+91 00000 00000",
      address: "123, Tech Street, Bengaluru, Karnataka - 560001",
      logoBase64: "",
    },
    client: {
      name: "",
      company: "",
      email: "",
      address: "",
    },
    metadata: {
      invoiceNumber: generateInvoiceNumber(),
      invoiceDate: today,
      dueDate: getDateAfterDays(30),
      status: "draft",
    },
    items: [createBlankItem()],
    gstRate: 18,
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
